name: Test examples

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with black
      run: |
        black --exclude venv/ --check .
    - name: Type check with mypy
      run: |
        mypy --exclude venv/ .
    - name: Test with pytest
      run: |
        pytest
      env:
        MONGODB_CONNECTION_STRING: "mongodb://localhost:27017"
